### PR TITLE
fix: add started at command detail sheet

### LINKED ISSUE #218: fix: add startedAt property in robot command
- duration phải tính từ lúc thực hiện tới lúc hoàn thành

Image

### LINKED ISSUE #232: Feat: add started at for command detail sheet

### PR DESCRIPTION
**Pull request by nguyen083**
close #232
close #218

### CODE REVIEW

File: ui/src/types/command.ts [hunk 1]
```diff
@@ -49,6 +49,7 @@ export interface Command<T extends CommandType = CommandType> {
   inputs: CommandInputMap[T]
   error?: string | null
   completedAt?: string | null
+  startedAt?: string | null
```
Comment (tuanvumaihuynh) [inline ui/src/types/command.ts:52]: Dont use null just undefined

**Review by tuanvumaihuynh — APPROVED** [review]
